# Generated by Django 4.0.4 on 2022-09-29 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ReceiptNumber', models.CharField(max_length=20)),
                ('TransactionNumber', models.CharField(max_length=20)),
                ('Semester', models.CharField(choices=[('1-Semester', '1-Semester'), ('2-Semester', '2-Semester'), ('3-Semester', '3-Semester'), ('4-Semester', '4-Semester'), ('5-Semester', '5-Semester'), ('6-Semester', '6-Semester'), ('7-Semester', '7-Semester'), ('8-Semester', '8-Semester')], max_length=20)),
                ('TuitionFee', models.IntegerField()),
                ('ExamFee', models.IntegerField()),
                ('Enrollmentfee', models.IntegerField()),
                ('RegistrationFee', models.IntegerField()),
                ('SecurityDeposited', models.IntegerField()),
                ('SportFee', models.IntegerField()),
                ('DevelopmentFee', models.IntegerField()),
                ('WelfareFee', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
