# Generated by Django 4.0.4 on 2022-09-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(blank=True, choices=[('2014-2018', '2014-2018'), ('2015-2019', '2015-2019'), ('2016-2020', '2016-2020'), ('2017-2021', '2017-2021'), ('2018-2022', '2018-2022'), ('2019-2023', '2019-2023'), ('2020-2024', '2020-2024'), ('2021-2025', '2021-2025'), ('2022-2026', '2022-2026')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, choices=[('Computer Science Engineering', 'Computer Science Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics & Communication', 'Electronics & Communication'), ('Electronics Engineering', 'Electronics Engineering'), ('Civil Engineering', 'Civil Engineering')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(blank=True, choices=[('1 semester', '1 semester'), ('2 semester', '2 semester'), ('3 semester', '3 semester'), ('4 semester', '4 semester'), ('5 semester', '5 semester'), ('6 semester', '6 semester'), ('7 semester', '7 semester'), ('8 semester', '8 semester')], max_length=200, null=True)),
                ('TuitionFee', models.IntegerField()),
                ('ExamFee', models.IntegerField()),
                ('EnrollmentFee', models.IntegerField()),
                ('RegistrationFee', models.IntegerField()),
                ('SecurityDeposited', models.IntegerField()),
                ('SportFee', models.IntegerField()),
                ('DevelopmentFee', models.IntegerField()),
                ('WelfareFee', models.IntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.branch')),
            ],
        ),
    ]
